FROM ${ECR_PHP_FPM_LATEST_BASE_IMAGE}

COPY docker-images/build/${UXMALTECH_APP_NAME} /www

RUN mkdir -p /www/storage/framework/sessions
RUN mkdir -p /www/storage/framework/views
RUN mkdir -p /www/storage/framework/cache

RUN chmod -R 777 /www/storage
RUN chmod -R 777 /www/bootstrap/cache

ENV PHP_FPM_ERROR_LOG=/proc/self/fd/2
ENV PHP_FPM_LOG_LEVEL=error
ENV PHP_FPM_LISTEN=0.0.0.0:${ECR_PHP_FPM_PORT}
ENV PHP_FPM_USER=www-data
ENV PHP_FPM_GROUP=www-data
ENV PHP_FPM_LISTEN_OWNER=www-data
ENV PHP_FPM_LISTEN_GROUP=www-data
ENV PHP_MEMORY_LIMIT=512M
ENV PHP_EXPOSE_PHP=On
ENV PHP_SESSION_GC_MAXLIFETIME=1440

EXPOSE ${ECR_PHP_FPM_PORT}
