# Use Alpine Linux
FROM php:8.2.13-apache

# Declare maintainer
LABEL \
    Maintainer="Enrique Martinez <https://uxmal.tech>" \
    Description="NGINX with extensions on top of Alpine Linux."

# Timezone
ENV TIMEZONE America/Monterrey

EXPOSE 8000
