# Use Alpine Linux
FROM uxmaltech/nginx-alpine$NGINX_ALPINE_VERSION:latest

# Declare maintainer
LABEL \
    version="${APP_TAG}" \
    Maintainer="${APP_AUTHOR} <${APP_EMAIL}>" \
    Description="${APP_NAME}:nginx:${APP_TAG}"

# Install dependencies
COPY docker-images/build/docker/conf/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /www/public
ADD docker-images/build/${APP_NAME}/public /www/public/
