version: '3.2'
services:
  ${NGINX_SERVICE_HOST}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/nginx/Dockerfile
    image: ${NGINX_APP_REPOSITORY_TAG}
    ports:
      - "${CLUSTER_PORT}:${NGINX_SERVICE_PORT}"
    depends_on:
      - ${PHP_FPM_SERVICE_HOST}
    networks:
      - app-network

  ${PHP_FPM_SERVICE_HOST}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/php-fpm/Dockerfile
    image: ${PHP_FPM_APP_REPOSITORY_TAG}
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
