# Use Alpine Linux
FROM ${ECR_NGINX_LATEST_BASE_IMAGE}

# Install dependencies
COPY docker-images/build/docker/conf/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /www/public
ADD docker-images/build/${UXMALTECH_APP_NAME}/public /www/public/

EXPOSE ${ECR_NGINX_PORT}
