version: '3.2'
services:
  ${ECR_NGINX_SERVICE_DN}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/nginx/Dockerfile
    image: ${ECR_NGINX_APP_IMAGE_TAG}
    ports:
      - "${ECR_NGINX_PORT}:${ECR_NGINX_PORT}"
    depends_on:
      - ${ECR_PHP_FPM_SERVICE_DN}
    networks:
      - app-network

  ${ECR_PHP_FPM_SERVICE_DN}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/php-fpm/Dockerfile
    image: ${ECR_PHP_FPM_APP_IMAGE_TAG}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
