version: '3.2'
services:
  ${ECR_NGINX_SERVICE_DN}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/nginx/Dockerfile
    image: ${ECR_NGINX_LATEST_BASE_IMAGE}
    ports:
      - "${ECR_NGINX_PORT}:${ECR_NGINX_PORT}"
    depends_on:
      - ${ECR_PHP_FPM_SERVICE_DN}
    networks:
      - app-network

  ${ECR_PHP_FPM_SERVICE_DN}:
    build:
      context: .
      dockerfile: ./docker-images/build/docker/php-fpm/Dockerfile
    image: ${ECR_PHP_FPM_LATEST_BASE_IMAGE}
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
