FROM ${ECR_PHP_FPM_LATEST_BASE_IMAGE}

COPY docker-images/build/${UXMALTECH_APP_NAME} /www

RUN mkdir -p /www/storage/framework/sessions
RUN mkdir -p /www/storage/framework/views
RUN mkdir -p /www/storage/framework/cache

RUN chmod -R 777 /www/storage
RUN chmod -R 777 /www/bootstrap/cache

CMD ["/usr/local/bin/php","/www/artisan", "octane:start", "--host=0.0.0.0"]

EXPOSE 8000

